travis:
  secure:
    BINSTAR_TOKEN: Lyjumw/irqJQua5t4xSlrcLWZEtwzrfMrLVQPBxaDz4fxPtcw7ne7TkLTyXq7o9PSU6DdtjAVcRqgWJFAbumzdsRtgLYKCvuoV7b3MTugKdRjsjcIygA3wjd+vND1Z8nnawrxQARTuv3KW4ElFOI1oGnwIggTCUk3DNB4sxb5JKDIzLN5b7h5ZuCgdkO98h3GDIZPyrFmWX6FAm5a5nd+KGQgCDdiLMnQnnIj/4VKjz9Anc66WL2LDMfhOGlErw03bxQqAF6gxaZJOI7l467deXx9Y41at2x1KyY88GVYU310mX+XqRgjeZLWnTpYxbbnk9G4k38VQrN5xb754GZx9pSEFuFsKKVE25/bQVBGH72mmFOzZQrxi3HDPkVSod89VOssWlUQjOUOYYT4WACB25KWl4pUnrdeYKkdvQFNcP2urddmXyRIR+KGuTNAFQHsgYL26TlR42XFMvkzXanmLLyDuOGbjEG8r2DoPC6DbGOsb6qTA527VFmDHUE8ukMJeDcLUBaFXv4TCKkVqowNdJwl70dK/ZnBr8NnH5i8ej6+P4XvViEh1jY3YenKj1WnRCAEmu2UnsGS4om8f5we60BO0rZWmQdD3VRe+3m+2H+7rzlNqeNANY99KvO9cp5GzeTotXTehTXJaDuHavAmB5L7b/NvB2KRh4mxrc0R/M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
